/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary:                  'var(--md-primary)',
        'on-primary':             'var(--md-on-primary)',
        'primary-container':      'var(--md-primary-container)',
        'on-primary-container':   'var(--md-on-primary-container)',
        secondary:                'var(--md-secondary)',
        'on-secondary':           'var(--md-on-secondary)',
        'secondary-container':    'var(--md-secondary-container)',
        'on-secondary-container': 'var(--md-on-secondary-container)',
        tertiary:                  'var(--md-tertiary)',
        'tertiary-container':      'var(--md-tertiary-container)',
        'on-tertiary-container':   'var(--md-on-tertiary-container)',
        surface:                  'var(--md-surface)',
        'surface-variant':        'var(--md-surface-variant)',
        'surface-container':      'var(--md-surface-container)',
        'surface-container-high': 'var(--md-surface-container-high)',
        'on-surface':             'var(--md-on-surface)',
        'on-surface-variant':     'var(--md-on-surface-variant)',
        outline:                  'var(--md-outline)',
        'outline-variant':        'var(--md-outline-variant)',
        error:                    'var(--md-error)',
        'error-container':        'var(--md-error-container)',
        'on-error-container':     'var(--md-on-error-container)',
        'on-error':               'var(--md-on-error)',
        'warning-container':      'var(--md-warning-container)',
        'on-warning-container':   'var(--md-on-warning-container)',
        'success-container':      'var(--md-success-container)',
        'on-success-container':   'var(--md-on-success-container)',
      },
      spacing: {
        xs:   '0.25rem',
        sm:   '0.5rem',
        md:   '1rem',
        lg:   '1.5rem',
        xl:   '2rem',
        '2xl':'3rem',
      },
      borderRadius: {
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
      },
      animation: {
        fadeIn:   'fadeIn 0.2s ease-in-out',
        slideUp:  'slideUp 0.3s ease-out',
        fadeInUp: 'fadeInUp 0.3s ease-out',
        slideIn:  'slideIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn:   { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp:  { '0%': { transform: 'translateY(4px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideIn:  { '0%': { opacity: '0', transform: 'translateX(-16px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
      },
    },
  },
  darkMode: 'class',
  plugins: [],
}
